#############################################################################################
# +---------------------------------------------------------------------------------------+ #
# |                                                                                       | #
# |     ░██████╗███╗░░██╗███████╗░█████╗░██╗░░██╗░░░░░██╗██╗░░░██╗███╗░░░███╗██████╗░     | #
# |     ██╔════╝████╗░██║██╔════╝██╔══██╗██║░██╔╝░░░░░██║██║░░░██║████╗░████║██╔══██╗     | #
# |     ╚█████╗░██╔██╗██║█████╗░░███████║█████═╝░░░░░░██║██║░░░██║██╔████╔██║██████╔╝     | #
# |     ░╚═══██╗██║╚████║██╔══╝░░██╔══██║██╔═██╗░██╗░░██║██║░░░██║██║╚██╔╝██║██╔═══╝░     | #
# |     ██████╔╝██║░╚███║███████╗██║░░██║██║░╚██╗╚█████╔╝╚██████╔╝██║░╚═╝░██║██║░░░░░     | #
# |     ╚═════╝░╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░░╚═════╝░╚═╝░░░░░╚═╝╚═╝░░░░░     | #
# |                                                                                       | #
# +---------------------------------------------------------------------------------------+ #
#############################################################################################

# +----------------------------------------------------------------------------------------+ #
# |                                                                                        | #
# |                                   ESSENTIAL SETTINGS                                   | #
# |                                                                                        | #
# |                Important settings that control how SneakJump functions.                | #
# |                                                                                        | #
# +----------------------------------------------------------------------------------------+ #

# Enable or disable SneakJump functionality
# Default: true
enabled: true
# Permission required to use sneak + jump
# Default: sneakjump.jump
permission: sneakjump.jump

# Minecraft gravity approximation used in jump calculation
# Default: 0.0882
gravity: 0.0882
# How many blocks high the player should jump when sneaking
# Default: 2, Maximum: 61 blocks (Minecraft limit, maybe I will fix it in the future...)
jump-height: 2
# Multiplier applied to vertical velocity each tick
# Default: 0.997
multiplier: 0.997
# List of worlds where SneakJump is active
# Only players in these worlds will be able to sneak + jump
# Default: ["world", "world_nether", "world_the_end"]
allowed-worlds:
  - world
  - world_nether
  - world_the_end

# Shows useful commands
# {0} replaces with a command label
# /sneakjump help
help-messages:
  - "§7=== §aSneakJump Commands §7==="
  - "§e/{0} help §8- §fShows this help message."
  - "§e/{0} reload §8- §fReloads the config."
# Reloads the config
# /sneakjump reload
reload-message: "§8[§aSneakJump§8] §fSuccessfully reloaded the config."

# Config version (do not modify)
version: 1
